package localhost3000.airshowapplication;

import android.support.v4.app.FragmentActivity;
import android.os.Bundle;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

import java.lang.reflect.Array;
import java.util.ArrayList;


public class Map extends FragmentActivity implements OnMapReadyCallback {

    //Generated by activity
    private GoogleMap mMap;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        //Generated by activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_map);
        // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);


    }

    @Override
    public void onMapReady(GoogleMap googleMap) {

        //Variables
        mMap = googleMap;
        AirshowInformationStorage Storage = new AirshowInformationStorage();
        //String[] BaseCoords = Storage.getBaseCoords(Storage.getBaseID());

        String[] BaseCoords = null;

        ArrayList<ParkingSpot> Spots = Storage.getParkingSpots();

        for (ParkingSpot spot : Spots)
        {
            if (spot != null)
                if (spot.getName().contains("AFB") || spot.getName().contains("AFRB") || spot.getName().contains("ARB"))
                {
                    BaseCoords = new String[]{null, spot.getName(), String.valueOf(spot.getXCoord()), String.valueOf(spot.getYCoord())};
                }
        }

        //Sets pin for the base to get directions to
        LatLng Pin = new LatLng(Double.valueOf(BaseCoords[2]), Double.valueOf(BaseCoords[3]));
        mMap.addMarker(new MarkerOptions().position(Pin).title(BaseCoords[1]));
        mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(Pin, 13));
    }
}
